import Head from "next/head";
import pino from "pino";
import styles from "../styles/Home.module.css";

const logger = pino({
  browser: {
    asObject: true,
    transmit: {
      level: "info",
      send: (level, logEvent) => {
        const data = logEvent.messages[0];

        const headers = {
          type: "application/json",
        };
        const { userAgent, deviceMemory, connection } = window.navigator;
        navigator.sendBeacon(
          "/api/log",
          new Blob(
            [
              JSON.stringify({
                data,
                userAgent,
                deviceMemory,
                connection: {
                  type: connection?.type,
                  effectiveType: connection?.effectiveType,
                  downlink: connection?.downlink,
                },
                level,
              }),
            ],
            headers
          )
        );
      },
    },
  },
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button
          onClick={() => {
            logger.info({ type: "btn", msg: "clicked" });
          }}
        >
          Click Me
        </button>
      </main>
    </div>
  );
}
