import Head from "next/head";
import { logger } from "../src/logging/client";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button
          onClick={() => {
            logger.info({ type: "btn", msg: "clicked" });
          }}
        >
          Click Me
        </button>
        <button
          onClick={() => {
            throw Error("Uh oh: 💣");
          }}
        >
          Cause an Error
        </button>
        <button
          onClick={() => {
            new Promise(() => {
              throw Error("I promise to 💣");
            });
          }}
        >
          Cause UnresolvedPromise
        </button>
      </main>
    </div>
  );
}
